"""
API Routes for Nugen Domain-Aligned Event Operations Intelligence.
HackCelestial 3.0 Task 2:
Base Model -> Alignment -> Domain Model -> Integration -> Inference.
"""

import logging
from typing import Dict, Any, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.services.nugen.schemas import (
    NugenStatusResponse,
    NugenOperationalAssessment,
    NugenAnalyzeRequest,
    NugenWhatIfRequest,
    NugenAlignmentManifestResponse
)
from app.services.nugen.service import get_nugen_service, NugenEventIntelligenceService
from app.services.nugen.alignment import NugenAlignmentManager
from app.services.nugen.dataset import ALIGNMENT_DATASET_ITEMS

logger = logging.getLogger("eventos.api.nugen")

router = APIRouter(prefix="/api/v1/nugen", tags=["Nugen Intelligence"])


@router.get("/status", response_model=NugenStatusResponse)
async def get_nugen_status(
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """
    Returns honest system status of Nugen Intelligence layer:
    - LIVE (connected to upstream aligned model)
    - MOCK (synthetic domain operational inference)
    - DEGRADED (fallback to deterministic physics/rule engine)
    Never exposes API keys.
    """
    return await service.get_status()


@router.post("/analyze", response_model=NugenOperationalAssessment)
async def analyze_event_state(
    request: NugenAnalyzeRequest,
    db: Session = Depends(get_db),
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """
    Executes domain operational assessment for an event.
    Evaluates fused crowd, weather, transport, and hospitality states.
    Forecasts safety threshold breaches and multi-hop cascading impacts.
    """
    try:
        assessment = await service.analyze_event_state(
            event_id=request.event_id,
            custom_scenario=request.custom_scenario,
            db=db
        )
        return assessment
    except Exception as e:
        logger.error(f"[NUGEN API] Analysis error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Nugen operational assessment failed: {str(e)}"
        )


@router.post("/what-if")
async def analyze_what_if(
    request: NugenWhatIfRequest,
    db: Session = Depends(get_db),
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """
    Counterfactual simulation: Runs Digital Twin scenario, then performs
    Nugen domain inference on both baseline and simulated states for comparative analysis.
    """
    try:
        event_id = request.event_id
        if not event_id:
            from app.models.database import EventDB
            event = db.query(EventDB).first()
            event_id = event.event_id if event else "EVENT-MUMBAI-DERBY"

        result = await service.analyze_what_if(
            event_id=event_id,
            scenario_name=request.scenario_name,
            precipitation_mm_h=request.precipitation_mm_h,
            wind_speed_kmh=request.wind_speed_kmh,
            temperature_c=request.temperature_c,
            duration_minutes=request.duration_minutes,
            db=db
        )
        return result
    except Exception as e:
        logger.error(f"[NUGEN API] What-if simulation error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"What-if simulation failed: {str(e)}"
        )


@router.get("/latest")
async def get_latest_assessment(
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """Returns the most recent operational assessment generated by Nugen."""
    if not service.latest_assessment:
        return {
            "status": "NO_ASSESSMENT_YET",
            "message": "No operational assessments have been generated in this session."
        }
    return service.latest_assessment.model_dump()


@router.get("/telemetry")
async def get_nugen_telemetry(
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """Returns execution telemetry, assessment counters, and audit history."""
    return service.get_telemetry()


@router.get("/alignment/manifest", response_model=NugenAlignmentManifestResponse)
def get_alignment_manifest():
    """
    Returns the formal Nugen Alignment Manifest detailing the transformation
    from Base AI Model to Domain-Aligned Event Operations Model.
    """
    manager = NugenAlignmentManager()
    return manager.get_alignment_manifest()


@router.get("/alignment/dataset")
def get_alignment_dataset():
    """
    Returns the curated domain operational alignment dataset
    used to align the base model for event operations intelligence.
    """
    return {
        "dataset_name": "eventos_domain_alignment_v1",
        "total_records": len(ALIGNMENT_DATASET_ITEMS),
        "records": ALIGNMENT_DATASET_ITEMS
    }


@router.post("/alignment/trigger")
async def trigger_alignment_sync(
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """
    Triggers or verifies the domain alignment workflow with the Nugen platform.
    Verifies dataset integrity and model deployment state.
    """
    manager = service.alignment_manager
    result = await manager.trigger_or_verify_alignment(service.client)
    return result


@router.post("/demo/simulate-incident")
async def simulate_closed_loop_incident(
    event_id: Optional[str] = Query(None, description="Event ID to run scenario on"),
    db: Session = Depends(get_db),
    service: NugenEventIntelligenceService = Depends(get_nugen_service)
):
    """
    Demonstrates the complete 15-step closed-loop deterministic scenario:
    Weather Shock -> Nugen Inference -> Forecast Breach -> Cascading Impact ->
    Resource Synthesis -> Human Approval Gate -> Staff Telegram Bot Dispatch ->
    Provider Feedback -> Digital Twin Reassessment -> Resolution.
    """
    try:
        if not event_id:
            from app.models.database import EventDB
            event = db.query(EventDB).first()
            event_id = event.event_id if event else "EVENT-MUMBAI-DERBY"

        result = await service.simulate_closed_loop_incident(event_id=event_id, db=db)
        return result
    except Exception as e:
        logger.error(f"[NUGEN DEMO] Closed-loop simulation error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Closed loop simulation failed: {str(e)}"
        )
